package com.bili.diushoujuaner.model.databasehelper.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.bili.diushoujuaner.model.databasehelper.dao.User;
import com.bili.diushoujuaner.model.databasehelper.dao.Friend;
import com.bili.diushoujuaner.model.databasehelper.dao.Party;
import com.bili.diushoujuaner.model.databasehelper.dao.Member;
import com.bili.diushoujuaner.model.databasehelper.dao.Chat;
import com.bili.diushoujuaner.model.databasehelper.dao.UpdateMark;

import com.bili.diushoujuaner.model.databasehelper.dao.UserDao;
import com.bili.diushoujuaner.model.databasehelper.dao.FriendDao;
import com.bili.diushoujuaner.model.databasehelper.dao.PartyDao;
import com.bili.diushoujuaner.model.databasehelper.dao.MemberDao;
import com.bili.diushoujuaner.model.databasehelper.dao.ChatDao;
import com.bili.diushoujuaner.model.databasehelper.dao.UpdateMarkDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig friendDaoConfig;
    private final DaoConfig partyDaoConfig;
    private final DaoConfig memberDaoConfig;
    private final DaoConfig chatDaoConfig;
    private final DaoConfig updateMarkDaoConfig;

    private final UserDao userDao;
    private final FriendDao friendDao;
    private final PartyDao partyDao;
    private final MemberDao memberDao;
    private final ChatDao chatDao;
    private final UpdateMarkDao updateMarkDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        friendDaoConfig = daoConfigMap.get(FriendDao.class).clone();
        friendDaoConfig.initIdentityScope(type);

        partyDaoConfig = daoConfigMap.get(PartyDao.class).clone();
        partyDaoConfig.initIdentityScope(type);

        memberDaoConfig = daoConfigMap.get(MemberDao.class).clone();
        memberDaoConfig.initIdentityScope(type);

        chatDaoConfig = daoConfigMap.get(ChatDao.class).clone();
        chatDaoConfig.initIdentityScope(type);

        updateMarkDaoConfig = daoConfigMap.get(UpdateMarkDao.class).clone();
        updateMarkDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        friendDao = new FriendDao(friendDaoConfig, this);
        partyDao = new PartyDao(partyDaoConfig, this);
        memberDao = new MemberDao(memberDaoConfig, this);
        chatDao = new ChatDao(chatDaoConfig, this);
        updateMarkDao = new UpdateMarkDao(updateMarkDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Friend.class, friendDao);
        registerDao(Party.class, partyDao);
        registerDao(Member.class, memberDao);
        registerDao(Chat.class, chatDao);
        registerDao(UpdateMark.class, updateMarkDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        friendDaoConfig.getIdentityScope().clear();
        partyDaoConfig.getIdentityScope().clear();
        memberDaoConfig.getIdentityScope().clear();
        chatDaoConfig.getIdentityScope().clear();
        updateMarkDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public FriendDao getFriendDao() {
        return friendDao;
    }

    public PartyDao getPartyDao() {
        return partyDao;
    }

    public MemberDao getMemberDao() {
        return memberDao;
    }

    public ChatDao getChatDao() {
        return chatDao;
    }

    public UpdateMarkDao getUpdateMarkDao() {
        return updateMarkDao;
    }

}
