package com.bili.diushoujuaner.model.databasehelper.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MEMBER".
 */
public class Member {

    private Long id;
    private long partyNo;
    private long userNo;
    /** Not-null value. */
    private String nickName;
    /** Not-null value. */
    private String addTime;
    private int type;

    public Member() {
    }

    public Member(Long id) {
        this.id = id;
    }

    public Member(Long id, long partyNo, long userNo, String nickName, String addTime, int type) {
        this.id = id;
        this.partyNo = partyNo;
        this.userNo = userNo;
        this.nickName = nickName;
        this.addTime = addTime;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getPartyNo() {
        return partyNo;
    }

    public void setPartyNo(long partyNo) {
        this.partyNo = partyNo;
    }

    public long getUserNo() {
        return userNo;
    }

    public void setUserNo(long userNo) {
        this.userNo = userNo;
    }

    /** Not-null value. */
    public String getNickName() {
        return nickName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /** Not-null value. */
    public String getAddTime() {
        return addTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

}
