package com.bili.diushoujuaner.model.databasehelper.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "UPDATE_MARK".
 */
public class UpdateMark {

    private Long id;
    private int tableNo;
    private String updateTime;

    public UpdateMark() {
    }

    public UpdateMark(Long id) {
        this.id = id;
    }

    public UpdateMark(Long id, int tableNo, String updateTime) {
        this.id = id;
        this.tableNo = tableNo;
        this.updateTime = updateTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getTableNo() {
        return tableNo;
    }

    public void setTableNo(int tableNo) {
        this.tableNo = tableNo;
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

}
