package com.bili.diushoujuaner.utils.entity.po;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MEMBER".
 */
public class Member {

    private Long id;
    private long partyNo;
    private long userNo;
    /** Not-null value. */
    private String memberName;
    /** Not-null value. */
    private String addTime;
    private int type;
    private boolean recent;

    public Member() {
    }

    public Member(Long id) {
        this.id = id;
    }

    public Member(Long id, long partyNo, long userNo, String memberName, String addTime, int type, boolean recent) {
        this.id = id;
        this.partyNo = partyNo;
        this.userNo = userNo;
        this.memberName = memberName;
        this.addTime = addTime;
        this.type = type;
        this.recent = recent;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getPartyNo() {
        return partyNo;
    }

    public void setPartyNo(long partyNo) {
        this.partyNo = partyNo;
    }

    public long getUserNo() {
        return userNo;
    }

    public void setUserNo(long userNo) {
        this.userNo = userNo;
    }

    /** Not-null value. */
    public String getMemberName() {
        return memberName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMemberName(String memberName) {
        this.memberName = memberName;
    }

    /** Not-null value. */
    public String getAddTime() {
        return addTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public boolean getRecent() {
        return recent;
    }

    public void setRecent(boolean recent) {
        this.recent = recent;
    }

}
